filebeat.inputs:
  - type: log
    enabled: true
    # Я запущу filebeat в докере и проброшу логи приложения по данному пути
    paths:
      #  - /host_metrics_app/host_metrics_app.log
        - /var/nginx/log/*.log
    # В fields мы можем указать дополнительные поля, а затем в logstash вытаскивать их
    # и делать какую-нибудь дополнительную работу с логами
    fields:
      # Название нашего сервиса
      service: product_nginx
      organisation: netology

output.logstash:
  hosts: ["logstash:5044"]
